- include: apt.yml
  when: ansible_os_family.id == 'Debian'
- include: yum.yml
  when: ansible_os_family.id == 'RedHat'

- name: include sudo supplementary group
  include_vars: "{{ family }}.yml"
- include: a.yml
- include: pushcx.yml
