---

- name: apt-get install lobsters dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  tags: pkg
  with_items:
    - cmake
    - g++
    - gcc
    - git
    - libc-dev
    - libsqlite3-dev
    - make
    - mariadb-client
    - nodejs
    - rails
    - ruby2.3
    - ruby2.3-dev
    - ruby-bundler
    - sqlite3

- name: apt-get install libmysqlclient-dev
  apt:
    name: libmysqlclient-dev
    state: present
  tags: pkg
  when: ansible_distribution == 'Ubuntu'

- name: apt-get install default-libmysqlclient-dev
  apt:
    name: default-libmysqlclient-dev
    state: present
  tags: pkg
  when: ansible_distribution == 'Debian'
