- include_tasks: apt.yml
  when: "'{{ ansible_os_family }}' == 'Debian'"
- include_tasks: yum.yml
  when: "'{{ ansible_os_family }}' == 'RedHat'"

# DKIM
# ----
# $ openssl genrsa -out dkim.key 1024
# $ openssl rsa -in dkim.key -out dkim.pub -pubout -outform PEM
# $ grep -v -e '^-' dkim.pub | tr -d '\n'

- name: cp /etc/default/opendkim
  copy: >
    src={{ item.name }}
    dest=/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - { name: 'etc/default/opendkim', mode: '0644' }
    - { name: 'etc/opendkim.conf',    mode: '0644' }

- name: cp /etc/aliases
  template: >
    src=etc/aliases
    dest=/etc/aliases
    owner=root
    group=root
    mode=644

- name: cp /etc/postfix
  register: postfix_config
  template: >
    src=etc/postfix/{{ item.name }}
    dest=/etc/postfix/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - { name: 'main.cf',   mode: '0644' }
    - { name: 'master.cf', mode: '0644' }
    - { name: 'transport', mode: '0644' }

- name: postmap
  when: postfix_config.changed
  shell: postmap /etc/postfix/transport

- name: postfix reload
  when: postfix_config.changed
  shell: postfix reload
