- include_tasks: apt.yml
  when: "'{{ ansible_os_family }}' == 'Debian'"
- include_tasks: yum.yml
  when: "'{{ ansible_os_family }}' == 'RedHat'"

- name: copy up unicorn config
  copy: >
    src="unicorn.conf.rb"
    dest="/srv/lobste.rs/http/config"
    owner=lobsters
    group=lobsters
    mode="0644"
